### ISSUE TITLE
Essence generation

### ISSUE THREAD

**Issue by DeflatedPickle** [DeflatedPickle/BugMagic#49]
#### Description
Bug essence. Is a difficult thing. It needs ways to be generated.

#### To-Do List
- [ ] Flowers and moulds that would release essence into the chunk every so often
- [ ] Edible mould you right-click on to break, poison you and give you some mana
- [ ] A spell to extract chunk mana
- [ ] Essence cookie. Rub it on the mould, it gets covered in essence. Eat it.
- [ ] A bottle to collect a bit of mana from mould and flowers

### Why should it be added?
Bug essence isn't easy to come by, it needs ways to be generated, both good and bad.

### How would it change things?
Players wouldn't have to throw away their wands after one use anymore.
